apiVersion: apps/v1
kind: Deployment
metadata:
  name: app_go
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: app_go
  template:
    metadata:
      labels:
        app: app_go

    spec:
      containers:
      - name: app_go
        image: img_app_go
        ports:
          containerPort: 8000

